Repository arduino/tooling-project-assets, pull requests merged in 2022-05, with the labels that each got.

#225 Bump all dependencies to current versions
  .github/workflows/check-python-task.yml
  .github/workflows/check-yaml-task.yml
  .github/workflows/spell-check-task.yml
  .github/workflows/test-python-poetry-task.yml
  workflow-templates/assets/cobra/docsgen/go.mod
  workflow-templates/assets/release-go-task/DistTasks.yml
  workflow-templates/check-go-dependencies-task.yml
  workflow-templates/check-go-task.yml
  workflow-templates/check-mkdocs-task.yml
  workflow-templates/check-python-task.md
  workflow-templates/check-python-task.yml
  workflow-templates/check-yaml-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-dependencies-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-mkdocs-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-python-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-yaml-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-mkdocs-poetry.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-mkdocs-versioned-poetry.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-crosscompile-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/spell-check-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-integration-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-python-poetry-task.yml
  workflow-templates/deploy-cobra-mkdocs-versioned-poetry.yml
  workflow-templates/deploy-mkdocs-poetry.md
  workflow-templates/deploy-mkdocs-poetry.yml
  workflow-templates/deploy-mkdocs-versioned-poetry.md
  workflow-templates/deploy-mkdocs-versioned-poetry.yml
  workflow-templates/release-go-crosscompile-task.yml
  workflow-templates/release-go-task.yml
  workflow-templates/spell-check-task.yml
  workflow-templates/test-go-integration-task.md
  workflow-templates/test-go-integration-task.yml
  workflow-templates/test-go-task.yml
  workflow-templates/test-python-poetry-task.md
  workflow-templates/test-python-poetry-task.yml
Labels: type: enhancement, topic: code

#223 Fallback to x86-64 release when macOS ARM 64-bit build not available
  other/installation-script/install.sh
Labels: type: imperfection, topic: code

#228 Standardize format of placeholders in templates
  .github/workflows/test-install-script.yml
  .markdown-link-check.json
  issue-templates/minimal/README.md
  issue-templates/template-choosers/general/config.yml
  issue-templates/template-choosers/github-actions/config.yml
  other/installation-script/README.md
  other/installation-script/install.sh
  other/installation-script/installation.md
  workflow-templates/README.md
  workflow-templates/assets/cobra/docsgen/go.mod
  workflow-templates/assets/cobra/docsgen/main.go
  workflow-templates/assets/general/gon.config.hcl
  workflow-templates/assets/mkdocs/mkdocs.yml
  workflow-templates/assets/test-integration/test_all.py
  workflow-templates/check-certificates.md
  workflow-templates/check-certificates.yml
  workflow-templates/check-general-formatting-task.md
  workflow-templates/check-go-dependencies-task.md
  workflow-templates/check-go-task.md
  workflow-templates/check-license.md
  workflow-templates/check-markdown-task.md
  workflow-templates/check-mkdocs-task.md
  workflow-templates/check-prettier-formatting-task.md
  workflow-templates/check-python-task.md
  workflow-templates/check-shell-task.md
  workflow-templates/check-taskfiles.md
  workflow-templates/check-toc-task.md
  workflow-templates/check-workflows-task.md
  workflow-templates/check-yaml-task.md
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-certificates.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-nightly-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-crosscompile-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
  workflow-templates/deploy-cobra-mkdocs-versioned-poetry.md
  workflow-templates/deploy-mkdocs-poetry.md
  workflow-templates/deploy-mkdocs-versioned-poetry.md
  workflow-templates/publish-go-nightly-task.md
  workflow-templates/publish-go-nightly-task.yml
  workflow-templates/publish-go-tester-task.md
  workflow-templates/release-go-crosscompile-task.md
  workflow-templates/release-go-crosscompile-task.yml
  workflow-templates/release-go-task.md
  workflow-templates/release-go-task.yml
  workflow-templates/release-tag.md
  workflow-templates/spell-check-task.md
  workflow-templates/sync-labels.md
  workflow-templates/test-go-integration-task.md
  workflow-templates/test-go-task.md
  workflow-templates/test-go-task.yml
  workflow-templates/test-python-poetry-task.md
Labels: topic: documentation, type: enhancement

#229 Split configuration file validation infrastructure by type
  .github/workflows/check-dependabot.yml
  .github/workflows/check-labels.yml
  .github/workflows/check-markdownlint.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#230 Return to using production version of markdownlint schema
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#231 Move docs for issue template chooser configs alongside assets
  issue-templates/minimal/README.md
  issue-templates/template-choosers/README.md
  issue-templates/template-choosers/general/README.md
  issue-templates/template-choosers/general/config.yml
  issue-templates/template-choosers/github-actions/README.md
  issue-templates/template-choosers/github-actions/config.yml
Labels: topic: documentation, type: enhancement

#232 Add a collection of reusable issue form configuration files
  .github/workflows/check-issue-templates.yml
  README.md
  Taskfile.yml
  issue-templates/forms/README.md
  issue-templates/forms/general/README.md
  issue-templates/forms/general/bug-report.yml
  issue-templates/forms/general/feature-request.yml
  issue-templates/forms/platform-dependent/README.md
  issue-templates/forms/platform-dependent/bug-report.yml
  issue-templates/forms/platform-dependent/feature-request.yml
Labels: type: enhancement, topic: code

#233 fix semver-tool version. 3.2.0 is downloaded but 3.0.0 is still used.
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-crosscompile-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
  workflow-templates/release-go-crosscompile-task.yml
  workflow-templates/release-go-task.yml
Labels: type: imperfection, topic: infrastructure

#234 Configure link check to use `Accept-Encoding` header for docs.github.com links
  .markdown-link-check.json
  workflow-templates/assets/check-markdown/.markdown-link-check.json
Labels: type: imperfection, topic: code

#235 Remove outdated action version specification from comments
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-nightly-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-crosscompile-task.yml
  workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
  workflow-templates/publish-go-nightly-task.yml
  workflow-templates/release-go-crosscompile-task.yml
  workflow-templates/release-go-task.yml
Labels: type: imperfection, topic: documentation
