Repository arduino/tooling-project-assets, pull requests merged in 2023-11, with the labels that each got.

#412 move to fork, since `mitchellh/gon` uses deprecated tooling and is archived
  workflow-templates/publish-go-nightly-task.md
  workflow-templates/publish-go-nightly-task.yml
  workflow-templates/release-go-crosscompile-task.md
  workflow-templates/release-go-crosscompile-task.yml
  workflow-templates/release-go-task.md
  workflow-templates/release-go-task.yml
Labels: type: enhancement

#418 [AE-45] Multipath options for `check-license.yml`
  .github/workflows/check-license.yml
  workflow-templates/check-license.md
  workflow-templates/check-license.yml
Labels: type: enhancement, topic: code

#419 Prevent uncontrolled file tree recursion while validating configuration files
  .github/workflows/check-npm-task.yml
  Taskfile.yml
  workflow-templates/assets/check-npm-task/Taskfile.yml
  workflow-templates/assets/npm-task/Taskfile.yml
  workflow-templates/check-npm-task.md
  workflow-templates/check-npm-task.yml
Labels: type: imperfection, topic: code, topic: infrastructure

#420 Use modern version of validator to validate Dependabot configuration files
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#421 Target specific scripts in "Check Scripts" template
  .github/workflows/check-shell-task.yml
  Taskfile.yml
  workflow-templates/assets/check-shell-task/Taskfile.yml
  workflow-templates/check-shell-task.md
  workflow-templates/check-shell-task.yml
Labels: type: imperfection, topic: code
