Repository arduino/tooling-project-assets, pull requests merged in 2023-03, with the labels that each got.

#326 Build releases simultaneously in `release-go-crosscompile-task` workflow
  workflow-templates/assets/release-go-crosscompile-task/DistTasks.yml
  workflow-templates/release-go-crosscompile-task.yml
Labels: type: enhancement, topic: code

#329 Fix `markdownlint-cli` version typo in `check-markdown-task` documentation
  workflow-templates/check-markdown-task.md
Labels: type: imperfection, topic: documentation

#332 Add infrastructure for checking project filesystem
  .github/workflows/check-files-task.yml
  README.md
  Taskfile.yml
  workflow-templates/assets/check-files-task/Taskfile.yml
  workflow-templates/check-files-task.md
  workflow-templates/check-files-task.yml
Labels: type: enhancement, topic: code, topic: infrastructure
